#!/usr/bin/env bash

command="${1}"
timeout="${2:-30}"

echo -e "\n\n\n=Running: $command=\n\n"

i=0
until eval "${command}"
do
  sleep 1
  ((i++))

  if [ "${i}" -gt "${timeout}" ]; then
      echo -e "\n\n\n=Command: $command="
      echo -e "failed, aborting due to ${timeout}s timeout!\n\n"
      exit 1
  fi
done

echo -e "\n\n\n= Done successfully running: $command =\n\n"
